### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by iulian0512** [surfstudio/flutter-swipe-refresh#25]
On pub.dev the package is advertised that it works on windows but running the example app in this repo on windows it does not appear to be working. In my opinion the windows support from pub.dev should be removed if it is not supported.

![image](https://user-images.githubusercontent.com/16035099/196676620-c04ed7d6-889b-4d93-a236-35cf37c74480.png)

**Comment by internetova** [comment]
@iulian0512 
Corrected. Will be updated in an upcoming release. 
https://github.com/surfstudio/flutter-swipe-refresh/pull/32
