### ISSUE TITLE
[BUG] Adaptive variant is only supported for iOS and Android

### ISSUE THREAD

**Issue by timovandeput** [surfstudio/flutter-swipe-refresh#28]
## Prior Issues

This bug could be related to this one:

https://github.com/surfstudio/flutter-swipe-refresh/issues/25

## Describe the bug

When using the `SwipeRefresh.adaptive()` constructor, it only resolves to an instance on iOS and Android.

Using this constructor on e.g. a desktop platform will therefore not work.

## Steps to Reproduce

Use the `.adaptive` constructor.

## What is the expected behavior?

MacOS and iOS should follow Cupertino, and all other platforms should follow Material.

## Additional context

Relates to: SwipeRefresh version 1.02

**Comment by internetova** [comment]
@timovandeput 
Corrected. Will be updated in an upcoming release. 
https://github.com/surfstudio/flutter-swipe-refresh/pull/32
